<?php

namespace Modules\Location\Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Database\Eloquent\Model;
use Modules\Location\Entities\Country;

class LocationDatabaseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Model::unguard();

        $countries = [
            ["name" => "Afghanistan", "phone_code" => "93", "iso_code" => "AF"],
            ["name" => "Albania", "phone_code" => "355", "iso_code" => "AL"],
            ["name" => "Algeria", "phone_code" => "213", "iso_code" => "DZ"],
            ["name" => "American Samoa", "phone_code" => "1-684", "iso_code" => "AS"],
            ["name" => "Andorra", "phone_code" => "376", "iso_code" => "AD"],
            ["name" => "Angola", "phone_code" => "244", "iso_code" => "AO"],
            ["name" => "Anguilla", "phone_code" => "1-264", "iso_code" => "AI"],
            ["name" => "Antarctica", "phone_code" => "672", "iso_code" => "AQ"],
            ["name" => "Antigua and Barbuda", "phone_code" => "1-268", "iso_code" => "AG"],
            ["name" => "Argentina", "phone_code" => "54", "iso_code" => "AR"],
            ["name" => "Armenia", "phone_code" => "374", "iso_code" => "AM"],
            ["name" => "Aruba", "phone_code" => "297", "iso_code" => "AW"],
            ["name" => "Australia", "phone_code" => "61", "iso_code" => "AU"],
            ["name" => "Austria", "phone_code" => "43", "iso_code" => "AT"],
            ["name" => "Azerbaijan", "phone_code" => "994", "iso_code" => "AZ"],
            ["name" => "Bahamas", "phone_code" => "1-242", "iso_code" => "BS"],
            ["name" => "Bahrain", "phone_code" => "973", "iso_code" => "BH"],
            ["name" => "Bangladesh", "phone_code" => "880", "iso_code" => "BD"],
            ["name" => "Barbados", "phone_code" => "1-246", "iso_code" => "BB"],
            ["name" => "Belarus", "phone_code" => "375", "iso_code" => "BY"],
            ["name" => "Belgium", "phone_code" => "32", "iso_code" => "BE"],
            ["name" => "Belize", "phone_code" => "501", "iso_code" => "BZ"],
            ["name" => "Benin", "phone_code" => "229", "iso_code" => "BJ"],
            ["name" => "Bermuda", "phone_code" => "1-441", "iso_code" => "BM"],
            ["name" => "Bhutan", "phone_code" => "975", "iso_code" => "BT"],
            ["name" => "Bolivia", "phone_code" => "591", "iso_code" => "BO"],
            ["name" => "Bosnia and Herzegovina", "phone_code" => "387", "iso_code" => "BA"],
            ["name" => "Botswana", "phone_code" => "267", "iso_code" => "BW"],
            ["name" => "Brazil", "phone_code" => "55", "iso_code" => "BR"],
            ["name" => "British Indian Ocean Territory", "phone_code" => "246", "iso_code" => "IO"],
            ["name" => "British Virgin Islands", "phone_code" => "1-284", "iso_code" => "VG"],
            ["name" => "Brunei", "phone_code" => "673", "iso_code" => "BN"],
            ["name" => "Bulgaria", "phone_code" => "359", "iso_code" => "BG"],
            ["name" => "Burkina Faso", "phone_code" => "226", "iso_code" => "BF"],
            ["name" => "Burundi", "phone_code" => "257", "iso_code" => "BI"],
            ["name" => "Cambodia", "phone_code" => "855", "iso_code" => "KH"],
            ["name" => "Cameroon", "phone_code" => "237", "iso_code" => "CM"],
            ["name" => "Canada", "phone_code" => "1", "iso_code" => "CA"],
            ["name" => "Cape Verde", "phone_code" => "238", "iso_code" => "CV"],
            ["name" => "Cayman Islands", "phone_code" => "1-345", "iso_code" => "KY"],
            ["name" => "Central African Republic", "phone_code" => "236", "iso_code" => "CF"],
            ["name" => "Chad", "phone_code" => "235", "iso_code" => "TD"],
            ["name" => "Chile", "phone_code" => "56", "iso_code" => "CL"],
            [
                "name" => "China", "phone_code" => "86", "iso_code" => "CN",
                'cities' => [
                    ["name" => "Guangzhou"],
                    ["name" => "Shanghai"],
                    ["name" => "Chongqing"],
                    ["name" => "Hangzhou"],
                    ["name" => "Wuhan"],
                    ["name" => "Chengdu"],
                    ["name" => "Tianjin"],
                    ["name" => "Xian"],
                    ["name" => "Jinan"],
                    ["name" => "Shenzen"],
                    ["name" => "Nanjing"],
                    ["name" => "Shenyang"],
                    ["name" => "Harbin"],
                    ["name" => "Shantou"],
                ]
            ],
            ["name" => "Christmas Island", "phone_code" => "61", "iso_code" => "CX"],
            ["name" => "Cocos Islands", "phone_code" => "61", "iso_code" => "CC"],
            ["name" => "Colombia", "phone_code" => "57", "iso_code" => "CO"],
            ["name" => "Comoros", "phone_code" => "269", "iso_code" => "KM"],
            ["name" => "Cook Islands", "phone_code" => "682", "iso_code" => "CK"],
            ["name" => "Costa Rica", "phone_code" => "506", "iso_code" => "CR"],
            ["name" => "Croatia", "phone_code" => "385", "iso_code" => "HR"],
            ["name" => "Cuba", "phone_code" => "53", "iso_code" => "CU"],
            ["name" => "Curacao", "phone_code" => "599", "iso_code" => "CW"],
            ["name" => "Cyprus", "phone_code" => "357", "iso_code" => "CY"],
            ["name" => "Czech Republic", "phone_code" => "420", "iso_code" => "CZ"],
            ["name" => "Democratic Republic of the Congo", "phone_code" => "243", "iso_code" => "CD"],
            ["name" => "Denmark", "phone_code" => "45", "iso_code" => "DK"],
            ["name" => "Djibouti", "phone_code" => "253", "iso_code" => "DJ"],
            ["name" => "Dominica", "phone_code" => "1-767", "iso_code" => "DM"],
            ["name" => "Dominican Republic", "phone_code" => "1-849", "iso_code" => "DO"],
            ["name" => "East Timor", "phone_code" => "670", "iso_code" => "TL"],
            ["name" => "Ecuador", "phone_code" => "593", "iso_code" => "EC"],
            ["name" => "Egypt", "phone_code" => "20", "iso_code" => "EG"],
            ["name" => "El Salvador", "phone_code" => "503", "iso_code" => "SV"],
            ["name" => "Equatorial Guinea", "phone_code" => "240", "iso_code" => "GQ"],
            ["name" => "Eritrea", "phone_code" => "291", "iso_code" => "ER"],
            ["name" => "Estonia", "phone_code" => "372", "iso_code" => "EE"],
            ["name" => "Ethiopia", "phone_code" => "251", "iso_code" => "ET"],
            ["name" => "Falkland Islands", "phone_code" => "500", "iso_code" => "FK"],
            ["name" => "Faroe Islands", "phone_code" => "298", "iso_code" => "FO"],
            ["name" => "Fiji", "phone_code" => "679", "iso_code" => "FJ"],
            ["name" => "Finland", "phone_code" => "358", "iso_code" => "FI"],
            ["name" => "France", "phone_code" => "33", "iso_code" => "FR"],
            ["name" => "French Polynesia", "phone_code" => "689", "iso_code" => "PF"],
            ["name" => "Gabon", "phone_code" => "241", "iso_code" => "GA"],
            ["name" => "Gambia", "phone_code" => "220", "iso_code" => "GM"],
            ["name" => "Georgia", "phone_code" => "995", "iso_code" => "GE"],
            ["name" => "Germany", "phone_code" => "49", "iso_code" => "DE"],
            ["name" => "Ghana", "phone_code" => "233", "iso_code" => "GH"],
            ["name" => "Gibraltar", "phone_code" => "350", "iso_code" => "GI"],
            ["name" => "Greece", "phone_code" => "30", "iso_code" => "GR"],
            ["name" => "Greenland", "phone_code" => "299", "iso_code" => "GL"],
            ["name" => "Grenada", "phone_code" => "1-473", "iso_code" => "GD"],
            ["name" => "Guam", "phone_code" => "1-671", "iso_code" => "GU"],
            ["name" => "Guatemala", "phone_code" => "502", "iso_code" => "GT"],
            ["name" => "Guernsey", "phone_code" => "44-1481", "iso_code" => "GG"],
            ["name" => "Guinea", "phone_code" => "224", "iso_code" => "GN"],
            ["name" => "Guinea-Bissau", "phone_code" => "245", "iso_code" => "GW"],
            ["name" => "Guyana", "phone_code" => "592", "iso_code" => "GY"],
            ["name" => "Haiti", "phone_code" => "509", "iso_code" => "HT"],
            ["name" => "Honduras", "phone_code" => "504", "iso_code" => "HN"],
            [
                "name" => "Hong Kong", "phone_code" => "852", "iso_code" => "HK",
                'cities' => [
                    ["name" => "Hong Kong"],
                    ["name" => "Kowloon"],
                    ["name" => "Tsuen Wan"],
                    ["name" => "Yuen Long Kau Hui"],
                    ["name" => "Tung Chung"],
                    ["name" => "Shatin"],
                    ["name" => "Tuen Mun"],
                    ["name" => "Tai Po"],
                    ["name" => "Sai Kung"],
                    ["name" => "Yung Shue Wan"],
                    ["name" => "Ngong Ping"],
                    ["name" => "Sok Kwu Wan"],
                ]
            ],
            ["name" => "Hungary", "phone_code" => "36", "iso_code" => "HU"],
            ["name" => "Iceland", "phone_code" => "354", "iso_code" => "IS"],
            [
                "name" => "India", "phone_code" => "91", "iso_code" => "IN",
                "cities" => [
                    ["name" => "Mumbai"],
                    ["name" => "Delhi"],
                    ["name" => "Bangalore"],
                    ["name" => "Hyderabad"],
                    ["name" => "Ahmedabad"],
                    ["name" => "Chennai"],
                    ["name" => "kolkota"],
                    ["name" => "Surat"],
                    ["name" => "Pune"],
                    ["name" => "Jaipur"],
                    ["name" => "Lucknow"],
                    ["name" => "Kanpur"],
                    ["name" => "Nagpur"],
                    ["name" => "Indore"],
                    ["name" => "Thane"],
                    ["name" => "Bhopal"],
                    ["name" => "Visakhapatnam"],
                    ["name" => "Patna"],
                    ["name" => "Vadodara"],
                    ["name" => "Ghaziabad"],
                    ["name" => "Ludhiana"],
                    ["name" => "Agra"],
                    ["name" => "Nashik"],
                    ["name" => "Faridabad"],
                    ["name" => "Meerut"],
                    ["name" => "Rajkot"],
                    ["name" => "Kalyan"],
                    ["name" => "Varanasi"],
                    ["name" => "Srinagar"],
                    ["name" => "Amritsar"],
                    ["name" => "Ranchi"],
                    ["name" => "Gwalior"],
                    ["name" => "Jodhpur"],
                    ["name" => "Guwahati"],
                    ["name" => "Chandigarh"],
                    ["name" => "Gurgaon"],
                    ["name" => "Gorakhpur"],
                    ["name" => "Noida"],
                    ["name" => "Jamshedpur"],
                    ["name" => "Kochi"],
                    ["name" => "Dehradun"],
                    ["name" => "Siliguri"],
                    ["name" => "Jhansi"],
                    ["name" => "Jammu"],
                    ["name" => "Udaipur"],
                    ["name" => "Gaya"],
                ]
            ],
            ["name" => "Indonesia", "phone_code" => "62", "iso_code" => "ID"],
            ["name" => "Iran", "phone_code" => "98", "iso_code" => "IR"],
            ["name" => "Iraq", "phone_code" => "964", "iso_code" => "IQ"],
            ["name" => "Ireland", "phone_code" => "353", "iso_code" => "IE"],
            ["name" => "Isle of Man", "phone_code" => "44-1624", "iso_code" => "IM"],
            ["name" => "Israel", "phone_code" => "972", "iso_code" => "IL"],
            ["name" => "Italy", "phone_code" => "39", "iso_code" => "IT"],
            ["name" => "Ivory Coast", "phone_code" => "225", "iso_code" => "CI"],
            ["name" => "Jamaica", "phone_code" => "1-876", "iso_code" => "JM"],
            ["name" => "Japan", "phone_code" => "81", "iso_code" => "JP"],
            ["name" => "Jersey", "phone_code" => "44-1534", "iso_code" => "JE"],
            ["name" => "Jordan", "phone_code" => "962", "iso_code" => "JO"],
            ["name" => "Kazakhstan", "phone_code" => "7", "iso_code" => "KZ"],
            ["name" => "Kenya", "phone_code" => "254", "iso_code" => "KE"],
            ["name" => "Kiribati", "phone_code" => "686", "iso_code" => "KI"],
            ["name" => "Kosovo", "phone_code" => "383", "iso_code" => "XK"],
            ["name" => "Kuwait", "phone_code" => "965", "iso_code" => "KW"],
            ["name" => "Kyrgyzstan", "phone_code" => "996", "iso_code" => "KG"],
            ["name" => "Laos", "phone_code" => "856", "iso_code" => "LA"],
            ["name" => "Latvia", "phone_code" => "371", "iso_code" => "LV"],
            ["name" => "Lebanon", "phone_code" => "961", "iso_code" => "LB"],
            ["name" => "Lesotho", "phone_code" => "266", "iso_code" => "LS"],
            ["name" => "Liberia", "phone_code" => "231", "iso_code" => "LR"],
            ["name" => "Libya", "phone_code" => "218", "iso_code" => "LY"],
            ["name" => "Liechtenstein", "phone_code" => "423", "iso_code" => "LI"],
            ["name" => "Lithuania", "phone_code" => "370", "iso_code" => "LT"],
            ["name" => "Luxembourg", "phone_code" => "352", "iso_code" => "LU"],
            ["name" => "Macau", "phone_code" => "853", "iso_code" => "MO"],
            ["name" => "Macedonia", "phone_code" => "389", "iso_code" => "MK"],
            ["name" => "Madagascar", "phone_code" => "261", "iso_code" => "MG"],
            ["name" => "Malawi", "phone_code" => "265", "iso_code" => "MW"],
            [
                "name" => "Malaysia", "phone_code" => "60", "iso_code" => "MY",
                "cities" => [
                    ["name" => "George Town"],
                    ["name" => "Kuala Lumpur"],
                    ["name" => "Ipoh"],
                    ["name" => "Kuching"],
                    ["name" => "Johor Bahru"],
                    ["name" => "Kota Kinabalu"],
                    ["name" => "Shah Alam"],
                    ["name" => "Malacca City"],
                    ["name" => "Alor Setar"],
                    ["name" => "Miri"],
                    ["name" => "Petaling Jaya"],
                    ["name" => "Kuala Terengganu"],
                    ["name" => "Iskandar Puteri"],
                    ["name" => "Seberang Perai"],
                    ["name" => "Seremban"],
                    ["name" => "Subang Jaya"],
                ]
            ],
            ["name" => "Maldives", "phone_code" => "960", "iso_code" => "MV"],
            ["name" => "Mali", "phone_code" => "223", "iso_code" => "ML"],
            ["name" => "Malta", "phone_code" => "356", "iso_code" => "MT"],
            ["name" => "Marshall Islands", "phone_code" => "692", "iso_code" => "MH"],
            ["name" => "Mauritania", "phone_code" => "222", "iso_code" => "MR"],
            ["name" => "Mauritius", "phone_code" => "230", "iso_code" => "MU"],
            ["name" => "Mayotte", "phone_code" => "262", "iso_code" => "YT"],
            ["name" => "Mexico", "phone_code" => "52", "iso_code" => "MX"],
            ["name" => "Micronesia", "phone_code" => "691", "iso_code" => "FM"],
            ["name" => "Moldova", "phone_code" => "373", "iso_code" => "MD"],
            ["name" => "Monaco", "phone_code" => "377", "iso_code" => "MC"],
            ["name" => "Mongolia", "phone_code" => "976", "iso_code" => "MN"],
            ["name" => "Montenegro", "phone_code" => "382", "iso_code" => "ME"],
            ["name" => "Montserrat", "phone_code" => "1-664", "iso_code" => "MS"],
            ["name" => "Morocco", "phone_code" => "212", "iso_code" => "MA"],
            ["name" => "Mozambique", "phone_code" => "258", "iso_code" => "MZ"],
            [
                "name" => "Myanmar", "phone_code" => "95", "iso_code" => "MM",
                "cities" => [
                    ["name" => "Yangon"],
                    ["name" => "Mandalay"],
                    ["name" => "Naypyidaw"],
                    ["name" => "Mawlamyine"],
                    ["name" => "Taunggyi"],
                    ["name" => "Monywa"],
                    ["name" => "Meiktila"],
                    ["name" => "Bago"],
                    ["name" => "Pathein"],
                    ["name" => "Mergui"],
                    ["name" => "Sittwe"],
                    ["name" => "Pyay"],
                    ["name" => "Pakokku"],
                    ["name" => "Myeik"],
                    ["name" => "Meiktila"],
                    ["name" => "Taungoo"],
                    ["name" => "Myingyan"],
                    ["name" => "Mogok"],
                    ["name" => "Magway"],
                    ["name" => "Sagaing"],
                    ["name" => "Dawei"],
                    ["name" => "Hakha"],
                ]
            ],
            ["name" => "Namibia", "phone_code" => "264", "iso_code" => "NA"],
            ["name" => "Nauru", "phone_code" => "674", "iso_code" => "NR"],
            [
                "name" => "Nepal", "phone_code" => "977", "iso_code" => "NP",
                "cities" => [
                    ["name" => "Bandipur"],
                    ["name" => "Besisahar"],
                    ["name" => "Bhadrapur"],
                    ["name" => "Bhaktapur"],
                    ["name" => "Bharatpur"],
                    ["name" => "Biratnagar"],
                    ["name" => "Birendranagar"],
                    ["name" => "Birganj"],
                    ["name" => "Birgunj"],
                    ["name" => "Birtamode"],
                    ["name" => "Butwal"],
                    ["name" => "Chandranigahpur"],
                    ["name" => "Charikot"],
                    ["name" => "Dadeldhura"],
                    ["name" => "Dailekh"],
                    ["name" => "Damak"],
                    ["name" => "Damauli"],
                    ["name" => "Darchula"],
                    ["name" => "Dasharathchand"],
                    ["name" => "Dhangadhi"],
                    ["name" => "Dhangarhi"],
                    ["name" => "Dhankuta"],
                    ["name" => "Dharan"],
                    ["name" => "Dhulikhel"],
                    ["name" => "Dhunche"],
                    ["name" => "Dipayal"],
                    ["name" => "Gaighat"],
                    ["name" => "Dhangarhi"],
                    ["name" => "Gaur"],
                    ["name" => "Gorkha"],
                    ["name" => "Gulariya"],
                    ["name" => "Hetauda"],
                    ["name" => "Ilam"],
                    ["name" => "Inaruwa"],
                    ["name" => "Itahari"],
                    ["name" => "Jajarkot"],
                    ["name" => "Jaleshwar"],
                    ["name" => "Janakpur"],
                    ["name" => "Jomsom"],
                    ["name" => "Jumla"],
                    ["name" => "Kalaiya"],
                    ["name" => "Kankarbhitta"],
                    ["name" => "Kathmandu"],
                    ["name" => "Khandbari"],
                    ["name" => "Kirtipur"],
                    ["name" => "Kodari"],
                    ["name" => "Lahan"],
                    ["name" => "Lekhnath"],
                    ["name" => "Lukla"],
                    ["name" => "Lumbini"],
                    ["name" => "Madhyapur"],
                    ["name" => "Thimi"],
                    ["name" => "Mahendranagar"],
                    ["name" => "Malangawa"],
                    ["name" => "Manang"],
                    ["name" => "Mangalsen"],
                    ["name" => "Namche Bazar"],
                    ["name" => "Nepalgunj"],
                    ["name" => "Okhaldhunga"],
                    ["name" => "Panauti"],
                    ["name" => "Parasi"],
                    ["name" => "Patan"],
                    ["name" => "Pokhara"],
                    ["name" => "Prithibinarayan"],
                    ["name" => "Putalibazar"],
                    ["name" => "Rajbiraj"],
                    ["name" => "Ratnanagar"],
                    ["name" => "Rumjatar"],
                    ["name" => "Siddharthanagar"],
                    ["name" => "Simikot"],
                    ["name" => "Simra"],
                    ["name" => "Sindhulimadi"],
                    ["name" => "Siraha"],
                    ["name" => "Syangboche"],
                    ["name" => "Tansen"],
                    ["name" => "Taplejung"],
                    ["name" => "Taulihawa"],
                    ["name" => "Tikapur"],
                    ["name" => "Tribhuvannagar"],
                    ["name" => "Tulsipur"],
                    ["name" => "Waling"],
                ]
            ],
            ["name" => "Netherlands", "phone_code" => "31", "iso_code" => "NL"],
            ["name" => "Netherlands Antilles", "phone_code" => "599", "iso_code" => "AN"],
            ["name" => "New Caledonia", "phone_code" => "687", "iso_code" => "NC"],
            ["name" => "New Zealand", "phone_code" => "64", "iso_code" => "NZ"],
            ["name" => "Nicaragua", "phone_code" => "505", "iso_code" => "NI"],
            ["name" => "Niger", "phone_code" => "227", "iso_code" => "NE"],
            ["name" => "Nigeria", "phone_code" => "234", "iso_code" => "NG"],
            ["name" => "Niue", "phone_code" => "683", "iso_code" => "NU"],
            ["name" => "North Korea", "phone_code" => "850", "iso_code" => "KP"],
            ["name" => "Northern Mariana Islands", "phone_code" => "1-670", "iso_code" => "MP"],
            ["name" => "Norway", "phone_code" => "47", "iso_code" => "NO"],
            ["name" => "Oman", "phone_code" => "968", "iso_code" => "OM"],
            ["name" => "Pakistan", "phone_code" => "92", "iso_code" => "PK"],
            ["name" => "Palau", "phone_code" => "680", "iso_code" => "PW"],
            ["name" => "Palestine", "phone_code" => "970", "iso_code" => "PS"],
            ["name" => "Panama", "phone_code" => "507", "iso_code" => "PA"],
            ["name" => "Papua New Guinea", "phone_code" => "675", "iso_code" => "PG"],
            ["name" => "Paraguay", "phone_code" => "595", "iso_code" => "PY"],
            ["name" => "Peru", "phone_code" => "51", "iso_code" => "PE"],
            ["name" => "Philippines", "phone_code" => "63", "iso_code" => "PH"],
            ["name" => "Pitcairn", "phone_code" => "64", "iso_code" => "PN"],
            ["name" => "Poland", "phone_code" => "48", "iso_code" => "PL"],
            ["name" => "Portugal", "phone_code" => "351", "iso_code" => "PT"],
            ["name" => "Puerto Rico", "phone_code" => "1-939", "iso_code" => "PR"],
            ["name" => "Qatar", "phone_code" => "974", "iso_code" => "QA"],
            ["name" => "Republic of the Congo", "phone_code" => "242", "iso_code" => "CG"],
            ["name" => "Reunion", "phone_code" => "262", "iso_code" => "RE"],
            ["name" => "Romania", "phone_code" => "40", "iso_code" => "RO"],
            ["name" => "Russia", "phone_code" => "7", "iso_code" => "RU"],
            ["name" => "Rwanda", "phone_code" => "250", "iso_code" => "RW"],
            ["name" => "Saint Barthelemy", "phone_code" => "590", "iso_code" => "BL"],
            ["name" => "Saint Helena", "phone_code" => "290", "iso_code" => "SH"],
            ["name" => "Saint Kitts and Nevis", "phone_code" => "1-869", "iso_code" => "KN"],
            ["name" => "Saint Lucia", "phone_code" => "1-758", "iso_code" => "LC"],
            ["name" => "Saint Martin", "phone_code" => "590", "iso_code" => "MF"],
            ["name" => "Saint Pierre and Miquelon", "phone_code" => "508", "iso_code" => "PM"],
            ["name" => "Saint Vincent and the Grenadines", "phone_code" => "1-784", "iso_code" => "VC"],
            ["name" => "Samoa", "phone_code" => "685", "iso_code" => "WS"],
            ["name" => "San Marino", "phone_code" => "378", "iso_code" => "SM"],
            ["name" => "Sao Tome and Principe", "phone_code" => "239", "iso_code" => "ST"],
            ["name" => "Saudi Arabia", "phone_code" => "966", "iso_code" => "SA"],
            ["name" => "Senegal", "phone_code" => "221", "iso_code" => "SN"],
            ["name" => "Serbia", "phone_code" => "381", "iso_code" => "RS"],
            ["name" => "Seychelles", "phone_code" => "248", "iso_code" => "SC"],
            ["name" => "Sierra Leone", "phone_code" => "232", "iso_code" => "SL"],
            [
                "name" => "Singapore", "phone_code" => "65", "iso_code" => "SG",
                "cities" => [
                    ["name" => "Bishan"],
                    ["name" => "Yishun"],
                    ["name" => "Queenstown"],
                    ["name" => "Singapore"],
                    ["name" => "Hougang"],
                    ["name" => "Choa Chu Kang"],
                    ["name" => "Clementi"],
                    ["name" => "Tampines"],
                    ["name" => "Toa Payoh"],
                    ["name" => "Serangoon"],
                    ["name" => "Pasir Ris"],
                    ["name" => "Bukit Batok"],
                    ["name" => "Bukit Panjang"],
                    ["name" => "Boon Lay"],
                    ["name" => "Jurong"],
                    ["name" => "Sembawang"],
                    ["name" => "Simpang"],
                    ["name" => "Sungei Kadut"],
                    ["name" => "Woodland"],
                    ["name" => "Mandai"],
                    ["name" => "Punggol"],
                    ["name" => "Seletar"],
                    ["name" => "Sengkang"],
                    ["name" => "Bedok"],
                    ["name" => "Changi"],
                    ["name" => "Geylang"],
                ]
            ],
            ["name" => "Sint Maarten", "phone_code" => "1-721", "iso_code" => "SX"],
            ["name" => "Slovakia", "phone_code" => "421", "iso_code" => "SK"],
            ["name" => "Slovenia", "phone_code" => "386", "iso_code" => "SI"],
            ["name" => "Solomon Islands", "phone_code" => "677", "iso_code" => "SB"],
            ["name" => "Somalia", "phone_code" => "252", "iso_code" => "SO"],
            ["name" => "South Africa", "phone_code" => "27", "iso_code" => "ZA"],
            ["name" => "South Korea", "phone_code" => "82", "iso_code" => "KR"],
            ["name" => "South Sudan", "phone_code" => "211", "iso_code" => "SS"],
            ["name" => "Spain", "phone_code" => "34", "iso_code" => "ES"],
            ["name" => "Sri Lanka", "phone_code" => "94", "iso_code" => "LK"],
            ["name" => "Sudan", "phone_code" => "249", "iso_code" => "SD"],
            ["name" => "Suriname", "phone_code" => "597", "iso_code" => "SR"],
            ["name" => "Svalbard and Jan Mayen", "phone_code" => "47", "iso_code" => "SJ"],
            ["name" => "Swaziland", "phone_code" => "268", "iso_code" => "SZ"],
            ["name" => "Sweden", "phone_code" => "46", "iso_code" => "SE"],
            ["name" => "Switzerland", "phone_code" => "41", "iso_code" => "CH"],
            ["name" => "Syria", "phone_code" => "963", "iso_code" => "SY"],
            [
                "name" => "Taiwan", "phone_code" => "886", "iso_code" => "TW",
                'cities' => [
                    ["name" => "Taipei"],
                    ["name" => "Kaohsiung City"],
                    ["name" => "Taichung"],
                    ["name" => "Tainan City"],
                    ["name" => "Banciao"],
                    ["name" => "Hsinchu"],
                    ["name" => "Taoyuan City"],
                    ["name" => "Keelung"],
                    ["name" => "Hualien City"],
                    ["name" => "Yuanlin"],
                    ["name" => "Nantou City"],
                    ["name" => "Douliu"],
                    ["name" => "Chungho"],
                    ["name" => "Zhongli"],
                    ["name" => "Sanchung"],
                    ["name" => "Fengshan"],
                    ["name" => "Tucheng"],
                    ["name" => "Chiayi"],
                ]
            ],
            ["name" => "Tajikistan", "phone_code" => "992", "iso_code" => "TJ"],
            ["name" => "Tanzania", "phone_code" => "255", "iso_code" => "TZ"],
            [
                "name" => "Thailand", "phone_code" => "66", "iso_code" => "TH",
                'cities' => [
                    ["name" => "Bangkok"],
                    ["name" => "Chiang Mai"],
                    ["name" => "Phitsanulok"],
                    ["name" => "Phuket"],
                    ["name" => "Pattaya"],
                    ["name" => "Ubon Ratchathani"],
                    ["name" => "Nonthaburi"],
                    ["name" => "Nakhon Ratchasima"],
                    ["name" => "Hat Yai"],
                    ["name" => "Udon Thani"],
                    ["name" => "Pak Kret"],
                    ["name" => "Chaophraya Surasak"],
                    ["name" => "Khon Kaen"],
                    ["name" => "Samut Prakan"],
                    ["name" => "Mueang Nonthaburi"],
                    ["name" => "Chon Buri"],
                    ["name" => "Si Racha"],
                    ["name" => "Phra Pradaeng"],
                    ["name" => "Lampang"],
                    ["name" => "Khon Kaen"],
                    ["name" => "Surat Thani"],
                    ["name" => "Nakhon Si Thammarat"],
                    ["name" => "Khlong Luang"],
                    ["name" => "Rayong"]
                ]
            ],
            ["name" => "Togo", "phone_code" => "228", "iso_code" => "TG"],
            ["name" => "Tokelau", "phone_code" => "690", "iso_code" => "TK"],
            ["name" => "Tonga", "phone_code" => "676", "iso_code" => "TO"],
            ["name" => "Trinidad and Tobago", "phone_code" => "1-868", "iso_code" => "TT"],
            ["name" => "Tunisia", "phone_code" => "216", "iso_code" => "TN"],
            ["name" => "Turkey", "phone_code" => "90", "iso_code" => "TR"],
            ["name" => "Turkmenistan", "phone_code" => "993", "iso_code" => "TM"],
            ["name" => "Turks and Caicos Islands", "phone_code" => "1-649", "iso_code" => "TC"],
            ["name" => "Tuvalu", "phone_code" => "688", "iso_code" => "TV"],
            ["name" => "U.S. Virgin Islands", "phone_code" => "1-340", "iso_code" => "VI"],
            ["name" => "Uganda", "phone_code" => "256", "iso_code" => "UG"],
            ["name" => "Ukraine", "phone_code" => "380", "iso_code" => "UA"],
            ["name" => "United Arab Emirates", "phone_code" => "971", "iso_code" => "AE"],
            ["name" => "UK", "phone_code" => "44", "iso_code" => "UK"],
            ["name" => "USA", "phone_code" => "1", "iso_code" => "US"],
            ["name" => "Uruguay", "phone_code" => "598", "iso_code" => "UY"],
            ["name" => "Uzbekistan", "phone_code" => "998", "iso_code" => "UZ"],
            ["name" => "Vanuatu", "phone_code" => "678", "iso_code" => "VU"],
            ["name" => "Vatican", "phone_code" => "379", "iso_code" => "VA"],
            ["name" => "Venezuela", "phone_code" => "58", "iso_code" => "VE"],
            ["name" => "Vietnam", "phone_code" => "84", "iso_code" => "VN"],
            ["name" => "Wallis and Futuna", "phone_code" => "681", "iso_code" => "WF"],
            ["name" => "Western Sahara", "phone_code" => "212", "iso_code" => "EH"],
            ["name" => "Yemen", "phone_code" => "967", "iso_code" => "YE"],
            ["name" => "Zambia", "phone_code" => "260", "iso_code" => "ZM"],
            ["name" => "Zimbabwe", "phone_code" => "263", "iso_code" => "ZW"]
        ];

        foreach ($countries as $country) {
            $columns = collect($country);
            $location = Country::create($columns->except('cities')->all());

            if (array_key_exists('cities', $country)) {
                foreach ($country['cities'] as $city) {
                    $location->cities()->create($city);
                }
            }

        }
    }
}
